platform :ios do

  lane :lint do
    swiftlint(
      mode: :lint,
      strict: true,
      raise_if_swiftlint_error: true
    )
  end

  private_lane :build_rockabye do |options|
    setup_ci
    update_code_signing_settings(
      use_automatic_signing: false,
      path: 'iosApp/iosApp.xcodeproj',
      targets: 'iosApp',
      profile_name: 'match AppStore com.joetr.bundle 1702321709',
    )
    update_code_signing_settings(
      use_automatic_signing: false,
      code_sign_identity: "Apple Distribution",
      path: 'iosApp/iosApp.xcodeproj'
    )
    sync_code_signing(
      type: "appstore",
      app_identifier: 'com.joetr.bundle',
      readonly: true
    )
    match(
      app_identifier: ["com.joetr.bundle"],
      type: options[:type] || "appstore"
    )
    build_app(
      export_method: "app-store",
      project: "iosApp/iosApp.xcodeproj",
      scheme: options[:scheme],
      buildlog_path: "build/fastlane-buildlog",
      skip_package_ipa: false,
      skip_codesigning: false,
    )
    end

  private_lane :release_rockabye do |options|
    setup_ci
    update_code_signing_settings(
      use_automatic_signing: false,
      path: 'iosApp/iosApp.xcodeproj',
      targets: 'iosApp',
      profile_name: 'match AppStore com.joetr.bundle 1702321709',
    )
    update_code_signing_settings(
      use_automatic_signing: false,
      code_sign_identity: "Apple Distribution",
      path: 'iosApp/iosApp.xcodeproj'
    )
    sync_code_signing(
      type: "appstore",
      app_identifier: 'com.joetr.bundle',
      readonly: true
    )
    match(
      app_identifier: ["com.joetr.bundle"],
      type: options[:type] || "appstore"
    )
    increment_build_number(
      xcodeproj: "iosApp/iosApp.xcodeproj",
      build_number: (ENV['ROCKABYE_BUILD_NUMBER'].to_i).to_s
    )
    build_app(
      export_method: "app-store",
      project: "iosApp/iosApp.xcodeproj",
      scheme: options[:scheme],
      buildlog_path: "build/fastlane-buildlog",
      skip_package_ipa: false,
      skip_codesigning: false,
    )
    app_store_connect_api_key(
      key_id: ENV['APP_STORE_CONNECT_API_KEY_KEY_ID'],
      issuer_id: ENV['APP_STORE_CONNECT_API_KEY_ISSUER_ID'],
      key_content: ENV['APP_STORE_CONNECT_API_KEY_KEY'],
      is_key_content_base64: true,
      duration: 1200,
    )

    upload_to_testflight(
        app_identifier: "com.joetr.bundle",
        skip_waiting_for_build_processing: true
    )
  end

  lane :build do
    lint()
    build_rockabye(scheme: "iosApp")
  end

  lane :release do
    lint()
    release_rockabye(scheme: "iosApp")
  end

end


platform :ios do

  desc "Get certificates"
  lane :certificates do
    sync_code_signing(
      type: "appstore",
      app_identifier: 'com.joetr.bundle',
      readonly: true
    )
  end
end